// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentMeetingPlanner_Sunday.Models;

namespace SacramentMeetingPlanner_Sunday.Migrations
{
    [DbContext(typeof(SacramentMeetingPlanner_SundayContext))]
    [Migration("20201215021653_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentMeetingPlanner_Sunday.Models.MeetingPlanner", b =>
                {
                    b.Property<int>("MeetingPlannerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClosingHymnNumber");

                    b.Property<string>("ClosingHymnTitle");

                    b.Property<string>("ClosingPrayer");

                    b.Property<string>("ConductingLeader");

                    b.Property<int>("IntermediateHymnNumber");

                    b.Property<string>("IntermediateHymnTitle");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<int>("OpeningHymnNumber");

                    b.Property<string>("OpeningHymnTitle");

                    b.Property<string>("OpeningPrayer");

                    b.Property<int>("SacramentHymnNumber");

                    b.Property<string>("SacramentHymnTitle");

                    b.HasKey("MeetingPlannerID");

                    b.ToTable("MeetingPlanner");
                });

            modelBuilder.Entity("SacramentMeetingPlanner_Sunday.Models.MeetingSpeaker", b =>
                {
                    b.Property<int>("MeetingSpeakerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MeetingPlannerID");

                    b.Property<string>("MeetingSpeakerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MeetingSpeakerTopic")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("MeetingSpeakerID");

                    b.ToTable("MeetingSpeaker");
                });
#pragma warning restore 612, 618
        }
    }
}
